# Generated by Django 2.1.7 on 2019-04-19 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_as', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='AdsPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_p1', models.TextField()),
                ('ads_p2', models.TextField()),
                ('ads_p3', models.TextField()),
                ('imag_p', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image_path)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdsPublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_1', models.TextField(default='ads')),
                ('ads_2', models.TextField(default='ads')),
                ('ads_3', models.TextField(default='ads')),
                ('ads_4', models.TextField(default='ads')),
                ('ads_5', models.TextField(default='ads')),
                ('ads_6', models.TextField(default='ads')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_name', models.CharField(max_length=200)),
                ('imag_dics', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image_path)),
                ('old_price', models.IntegerField(default=0)),
                ('new_price', models.IntegerField(default=0)),
                ('dis_phone', models.TextField()),
                ('date_pup', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
                ('text_1', models.TextField()),
                ('img_1', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image_path)),
                ('visit_num', models.PositiveIntegerField(default=1)),
                ('text_2', models.TextField()),
                ('img_2', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image_path)),
                ('img_3', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image_path)),
                ('img_4', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image_path)),
                ('text_3', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.AdsPersonal')),
            ],
        ),
    ]
