# Generated by Django 2.1.7 on 2019-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relate1_url',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='post',
            name='relate2_url',
            field=models.URLField(default='', max_length=20000),
        ),
    ]
