# Generated by Django 2.1.7 on 2019-06-04 18:23

from django.db import migrations, models
import django.utils.timezone
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190503_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspersonal',
            name='ads_p1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adspersonal',
            name='ads_p2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adspersonal',
            name='ads_p3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adspersonal',
            name='imag_p',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=post.models.upload_image_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adspublic',
            name='ads_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adspublic',
            name='ads_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adspublic',
            name='ads_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adspublic',
            name='ads_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adspublic',
            name='ads_5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adspublic',
            name='ads_6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_2',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=post.models.upload_image_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='img_3',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=post.models.upload_image_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='img_4',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=post.models.upload_image_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='relate1_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='relate2_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_url1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_url2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
