# Generated by Django 2.1.7 on 2019-06-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190604_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='dis_phone',
        ),
    ]
